[feat-qm] Add synchrony metrics to quality metrics
SpikeInterface/spikeinterface pull request #1205
Opened 2023-01-18 16:37 UTC by Moritz-Alexander-Kern

This PR is adding a metric for the presence of synchronous spiking events across multiple spike trains.

This is used to characterize synchronous events within the same spike train and across different spike
trains. This way synchronous events can be found both in multi-unit and single-unit spike trains.

The code was adapted from  [Elephant - Electrophysiology Analysis Toolkit](https://github.com/NeuralEnsemble/elephant/blob/master/elephant/spike_train_synchrony.py), see docs for more information 
[Spike train synchrony](https://elephant.readthedocs.io/en/latest/reference/_spike_train_processing.html#module-elephant.spike_train_synchrony)

2023-01-18 16:47 UTC, alejoe91 commented
Thanks @Moritz-Alexander-Kern! I'll provide some feedback soon

2023-01-18 16:53 UTC, alejoe91 requested changes
First round of feedback! Looks good, but I'd rather have the low-level implementation of the `annotate_synchrofacts` here rather than depending on elephant just for that function.

Could you also add tests in the `quality_metrics/tests/test_metric_functions.py`?

2023-01-18 16:53 UTC, alejoe91 commented on spikeinterface/qualitymetrics/misc_metrics.py
> +        f'syncSpike_{synchrony_size}': {
Use snake case

2023-01-19 13:04 UTC, Moritz-Alexander-Kern commented on spikeinterface/qualitymetrics/misc_metrics.py
> +        f'syncSpike_{synchrony_size}': {
```suggestion
        f'sync_spike_{synchrony_size}': {
```

2023-01-20 09:44 UTC, Moritz-Alexander-Kern commented on pyproject.toml
> +    "elephant>=0.11.0"
Thanks for the feedback, I see your point.

Please allow me some time to look into this.

2023-01-20 09:49 UTC, alejoe91 commented on pyproject.toml
> +    "elephant>=0.11.0"
Of course :) no rush!

2023-02-22 10:15 UTC, alejoe91 commented
@Moritz-Alexander-Kern @musall any update on this?

2023-02-22 10:25 UTC, Moritz-Alexander-Kern commented
Update: Currently porting the code from elephant. 

Following your suggestion to port the code from elephant to spikeinterface. I'm in the process of implementing this change and will update you once it is complete.

2023-05-03 08:53 UTC, alejoe91 commented
Hi @Moritz-Alexander-Kern 

We recently changed the main branch to `main` instead of `master`.

We should not port the full `elephant` classes here, but just the minimal function required to find synchronous events (`annotate_synchrofacts`), which should take numpy array as inputs. 

Would you have time to work on this?

2023-09-01 14:27 UTC, alejoe91 commented
Closing in favor of #1951

2023-09-01 14:27 UTC, closed without merging