refactor run_sorter() for hither (docker) integration
SpikeInterface/spikeinterface pull request #168
Opened 2021-05-28 13:01 UTC by samuelgarcia

2021-06-01 19:17 UTC, samuelgarcia commented
@alejoe91 @bendichter : this is a dead simple and working implementation of running a sorters into a docker using the python `docker` package.

The only constrain is that the docker need to have spiekinterface 0.90.0 inside which is possible only with source at the moment.
After July, we will be able to made collection od docker image with it.

Compared to the version using `hither` done by Alessio (in the old API), here the `docker_image='...'` can be change on demand and is not hard coded in sources.
This will be super convinient to test differents version of the same sorter within the same code.

Please make some feedback.

@alejoe91  : If you validate, I will made a small doc also.

2021-06-03 20:25 UTC, samuelgarcia commented
@alejoe91 : if you have 3 minuts tomorow, could you approve this PR. So we can merge.
I will need to make demo soon.
We will be able to improve docker stuff later.
Thanks a lot.

2021-06-03 20:44 UTC, alejoe91 commented on spikeinterface/sorters/runsorter.py
> +def modify_input_folder(rec_dict, input_folder):
@samuelgarcia this should also handle lists of paths (see the `relative_to` in base.py)

2021-06-03 20:45 UTC, alejoe91 commented on spikeinterface/sorters/runsorter.py
> +    assert output_folder is not None, 'with run in docker output_folder must be specify'
We could also set the same default folder as in the local version

2021-06-03 20:50 UTC, alejoe91 requested changes
@samuelgarcia this looks great! Just have a couple of comments

2021-06-04 09:33 UTC, samuelgarcia commented
Thank you for review.
Changes done.

2021-06-04 10:53 UTC, alejoe91 approved these changes

2021-06-04 11:12 UTC, merged