Sorter relative path
SpikeInterface/spikeinterface pull request #1737
Opened 2023-06-22 15:17 UTC by miketrumpis

This set of changes exposes functionality to make sorting runs using a relative path for the recording, by exposing these options

* `relative_to` option for `BaseExtractor.dump_to_json`
* `base_folder` option in `spikeinterface.core.base.load_extractor`

The keyword `recording_relative_path` is added to a few signatures in `BaseSorter`.
The bulk of the diffs propagate the options overloads of `BaseSorter._run_from_folder`

2023-06-23 07:44 UTC, alejoe91 requested changes
THanks @miketrumpis 

I would "unify" the API by directly using the `relative_to` instead of the `recording_relative_path`. I think this is clear enough :)

What do you think?

2023-06-23 16:01 UTC, miketrumpis commented
Happy to search-n-replace if that's your preference, but what about `base_folder`?

2023-06-24 08:37 UTC, alejoe91 commented
Thanks! `base_folder` is when loading the object, so I think that the meaning is a bit different hence the different name

2023-06-30 10:00 UTC, samuelgarcia commented
Hi @miketrumpis : are you ok to close ?

2023-06-30 15:55 UTC, closed without merging

2023-06-30 15:55 UTC, miketrumpis commented
Yup!