Implement Spike retriever
SpikeInterface/spikeinterface pull request #1944
Opened 2023-08-29 07:26 UTC by samuelgarcia

Need #1941 to be merged before.

SpikeRetriever class is usefull to inject a sorting object in the node pipepline mechanisim.
It allows to compute some post processing with the same machinery used for sorting components.
This is a first step to totaly refactor: 
  * compute_spike_locations()
  * compute_amplitude_scalings()
  * compute_spike_amplitudes()
  * compute_principal_components()

2023-09-01 07:16 UTC, samuelgarcia commented
@alejoe91 this is ready to be reviewed/merged

2023-09-01 14:42 UTC, alejoe91 requested changes
Thanks @samuelgarcia 

A few comments and suggestions!

2023-09-01 14:42 UTC, alejoe91 commented on src/spikeinterface/core/node_pipeline.py
> +
missing

2023-09-01 14:42 UTC, alejoe91 commented on src/spikeinterface/core/node_pipeline.py
> +    This class is usefull to inject a sorting object in the node pipepline mechanisim.
```suggestion
    This class is useful to inject a sorting object in the node pipepline mechanism.
```

2023-09-01 14:42 UTC, alejoe91 commented on src/spikeinterface/core/node_pipeline.py
> +    It allows to compute some post processing with the same machinery used for sorting components.
```suggestion
    It allows to compute some post-processing steps with the same machinery used for sorting components.
```

2023-09-01 14:42 UTC, alejoe91 commented on src/spikeinterface/core/node_pipeline.py
> +    This is a first step to totaly refactor:
Docstring should be as static as possible...
```suggestion
    This is used by:
```

2023-09-01 14:42 UTC, alejoe91 commented on src/spikeinterface/core/node_pipeline.py
> +        If True then the channel_index is infered from template and extremum_channel_inds must be provided.
```suggestion
        If True, then the channel_index is inferred from the template and `extremum_channel_inds` must be provided.
```

2023-09-01 14:42 UTC, alejoe91 commented on src/spikeinterface/core/node_pipeline.py
> +        If False every spikes compute its own channel index given a radius around the template max channel.
```suggestion
        If False, the max channel is computed for each spike given a radius around the template max channel.
```

2023-09-01 14:42 UTC, alejoe91 commented on src/spikeinterface/core/node_pipeline.py
> +def sorting_to_peak(sorting, extremum_channel_inds):
```suggestion
def sorting_to_peaks(sorting, extremum_channel_inds):
```

2023-09-01 14:42 UTC, alejoe91 commented on src/spikeinterface/core/tests/test_node_pipeline.py
> +    sorting_to_peak,
```suggestion
    sorting_to_peaks,
```

2023-09-01 14:42 UTC, alejoe91 commented on src/spikeinterface/core/tests/test_node_pipeline.py
> +    job_kwargs = dict(chunk_duration="0.5s", n_jobs=1, progress_bar=False)
why not 2 jobs?

2023-09-01 14:42 UTC, alejoe91 commented on src/spikeinterface/core/tests/test_node_pipeline.py
> +    # test with 2 diffrents first node
```suggestion
    # test with 3 differents first nodes
```

2023-09-13 14:39 UTC, alejoe91 commented on src/spikeinterface/core/node_pipeline.py
> +        assert extremum_channel_inds is not None, "SpikeRetriever need the dict extremum_channel_inds"
```suggestion
        assert extremum_channel_inds is not None, "SpikeRetriever needs the extremum_channel_inds dictionary"
```

2023-09-13 14:41 UTC, alejoe91 approved these changes

2023-09-13 14:41 UTC, merged