Change some default parameters for better user experience
SpikeInterface/spikeinterface pull request #2071
Opened 2023-10-04 14:05 UTC by samuelgarcia

Change some default parameters for better user experience

2023-10-05 08:17 UTC, alejoe91 commented
Not sure with sparsity=True by default. I would throw a warning for num_channels > 64

2023-10-05 09:57 UTC, samuelgarcia commented
For the user experience sparsity=True make everything faster with less disk space.
Even for 32 channels it is better.
I do not see why we should have the "bad" default option and make a warning to user saying : "hey you should use the other option!"

2023-10-05 11:08 UTC, zm711 commented
I just want to throw a vote Sam's way on this one. I often forget to set sparsity to True when I'm doing tests on things and so this would be a nice change for me. My logic being : 1) it helps me, 2) so many people are dealing with probes of >32 channels so making the default the better (again my opinion) option and then letting people with smaller probes switch to false if they want seems better. 

But I could be convinced the other direction, just my gut and disk space is with Sam on this one.

2023-10-05 11:09 UTC, samuelgarcia commented on src/spikeinterface/core/waveform_extractor.py
> +    sparse: bool (default True)
```suggestion
    sparse: bool, default: True
```

2023-10-05 11:14 UTC, alejoe91 approved these changes

2023-10-05 11:32 UTC, alejoe91 requested changes
I think that default sparsity is messing up with all prosptocessing tests. @samuelgarcia can you fix that?

2023-10-05 13:32 UTC, samuelgarcia commented
> I just want to throw a vote Sam's way on this one.

I am so happy

> I  think that default sparsity is messing up with all prosptocessing tests. @samuelgarcia can you fix that?

I will try my best.

2023-10-06 09:13 UTC, alejoe91 approved these changes

2023-10-06 09:13 UTC, merged