Move `comparison.hybrid.generate_injected_sorting` to `core.generate`
SpikeInterface/spikeinterface pull request #2253
Opened 2023-11-23 15:18 UTC by alejoe91

Fixes #1976

2023-11-24 10:14 UTC, h-mayorquin requested changes
This looks OK, to me. It is just moving as in the issue. Just let's add a sed as in the issue.

The docstring is a bonus but not necessary for me, we can do later.

2023-11-24 10:14 UTC, h-mayorquin commented on src/spikeinterface/core/generate.py
> +            n = int(n_injection + 10 * np.sqrt(n_injection))
I think from the issue we are missing the seed, right?

2023-11-24 10:14 UTC, h-mayorquin commented on src/spikeinterface/core/generate.py
> +    Generates a sorting object with injected spikes from an existing sorting object.
Can we take this cahnce to improve this docstring a little bit. I don't really understand what this object does.

Is it a sorting object that has spikes sampled from another sorting?

2023-12-13 10:20 UTC, alejoe91 commented
Closing in favor of #1999

2023-12-13 10:20 UTC, closed without merging