Fixed parent spike_vector bug
SpikeInterface/spikeinterface pull request #2418
Opened 2024-01-19 12:42 UTC by DradeAW

Fixed a bug introduced in #2353 where the spike vector would be wrong if the given unit_ids were non ordered.

2024-01-19 12:58 UTC, samuelgarcia approved these changes

2024-01-23 10:32 UTC, samuelgarcia commented on src/spikeinterface/curation/remove_excess_spikes.py
> +        for segment_index in range(1 + parent_spike_vector["segment_index"][-1]):
sorting.get_numsegments() woulkd be safer!!
You can have no spikes on the last segment for instance.

2024-01-23 10:35 UTC, alejoe91 commented on src/spikeinterface/curation/remove_excess_spikes.py
> +        for segment_index in range(1 + parent_spike_vector["segment_index"][-1]):
Also, the why do you need the `2 + ...` at L59? Can you add a comment about i?

2024-01-23 10:35 UTC, alejoe91 requested changes
See comments

2024-01-29 08:44 UTC, DradeAW commented on src/spikeinterface/curation/remove_excess_spikes.py
> +        for segment_index in range(1 + parent_spike_vector["segment_index"][-1]):
Well we need `2+` because we want the bounds, so we will access index `i+1` at some point.
Does it really need a comment?

2024-01-29 09:13 UTC, alejoe91 commented
@DradeAW can you check why tests are failing?

2024-01-29 12:27 UTC, DradeAW commented
Fixed!

It was a typo in the tests ^^'

2024-01-29 15:23 UTC, alejoe91 approved these changes

2024-01-31 12:40 UTC, samuelgarcia approved these changes

2024-01-31 12:40 UTC, merged