Add bit depth compensation to unsigned_to_signed
SpikeInterface/spikeinterface pull request #2438
Opened 2024-01-25 14:32 UTC by BptGrm

Circling back to NeuralEnsemble/python-neo#1348 : 

This PR, as is, returns correct traces from BioCAM recordings when processed through 
`signed_rec = spre.unsigned_to_signed(recording,bit_depth=12)`.

Looking at traces with : 
```
traces = recording.get_traces(channel_ids=['35','26','15','23','8'],
                               end_frame=4096) # Picking a few random channels
plt.plot(traces)
```
Raw  : 
![raw](https://github.com/SpikeInterface/spikeinterface/assets/83828302/0b6d177a-c11e-4775-ad3a-c9d4663993d9)

Processed : 
![processed](https://github.com/SpikeInterface/spikeinterface/assets/83828302/78edab6b-8008-48b3-8b85-14e0193a31f6)

A few questions : 

 - I'm not sure which version of numpy was around when this function was written, but on line 23 : 
 https://github.com/SpikeInterface/spikeinterface/blob/c2f18bd536437e9f500a4e24f7a0f3773bd79d3a/src/spikeinterface/preprocessing/unsigned_to_signed.py#L23
`dtype.str` now returns the data type as byte order + kind + item size, which means that `.replace("uint", "int")` does nothing and `dtype_signed` ends up being the same as `dtype`, thus traces get returned with the same data type as the raw recording.
I believe `dtype.name` behaves as expected.

 - Also might be related to numpy version, but `.astype()` does not seem to change the value of an array when doubling bit depth as in here : 
 https://github.com/SpikeInterface/spikeinterface/blob/c2f18bd536437e9f500a4e24f7a0f3773bd79d3a/src/spikeinterface/preprocessing/unsigned_to_signed.py#L47-L51

I'm not sure why substracting an offset is necessary in this situation. In fact, when looking at processed traces with the correct data type but the current offset calculations, the traces look like this : 
![offset](https://github.com/SpikeInterface/spikeinterface/assets/83828302/fd7227c7-0ef5-4c2b-a4d4-d595580165f9)
Which is about the calculated offset minus the 12 bits offset (32768 - 2048 = 30720).

 - Should the 12 bits offset compensation be on by default when open recordings through the BioCAM extractor ? Or at least some kind of warning when opening non-compensated recordings ?

 - I'm not sure in which use case this function is meant to be used, but are there any situations where having a signed data type might cause issues ?

2024-01-25 14:37 UTC, alejoe91 commented on src/spikeinterface/preprocessing/unsigned_to_signed.py
> +        bit_depth=None,
If None, it should automatically use the full range IMO:

e.g., `int16` --> `bit_dept=16`

What do you think @BptGrm ?

2024-01-25 14:37 UTC, alejoe91 commented on src/spikeinterface/preprocessing/unsigned_to_signed.py
> +        bit_depth=None,
Can you add docstrings as well below the class definition to explain this new behavior?

2024-01-25 14:38 UTC, alejoe91 commented on src/spikeinterface/preprocessing/unsigned_to_signed.py
> +            offset = 0
```suggestion
            offset = 2 ** (nbits - 1)
```
The old behavior should be default. In general, we can assume ADCs are used full range

2024-01-25 14:45 UTC, alejoe91 requested changes
See comments

2024-01-25 15:16 UTC, BptGrm commented
Sorry, I didn't fully understand the default behavior before. Should be clearer now.

2024-01-26 09:17 UTC, alejoe91 commented
Thansk for the changes! Last request: could you add a small test here that uses the new `bit_depth` argument?

https://github.com/SpikeInterface/spikeinterface/blob/main/src/spikeinterface/preprocessing/tests/test_unsigned_to_signed.py

2024-01-26 10:30 UTC, BptGrm commented
I hope it's enough, tests are passing for me locally.

2024-01-26 12:30 UTC, alejoe91 approved these changes

2024-01-29 09:51 UTC, alejoe91 approved these changes

2024-01-29 09:51 UTC, merged