Waveform extractor std
SpikeInterface/spikeinterface pull request #249
Opened 2021-09-01 14:41 UTC by Saksham20

creating method to extract waveform standard deviation for every time point. 
Just like templates which are either a mean or median across different spikes, this method finds the standard deviation across the spikes for every time point.

2021-09-02 02:59 UTC, Saksham20 commented on spikeinterface/core/waveform_extractor.py
> +            The returned waveform (num_spikes, num_samples, num_channels)
This is an error in orientation. Even in tests its this changed dimension order.

2021-09-02 07:46 UTC, alejoe91 commented
Hi @Saksham20 

I think it's easier to just change the `get_template` method and add the option `std` on top of average and median.

2021-09-02 09:21 UTC, Saksham20 commented
> Hi @Saksham20
> 
> I think it's easier to just change the `get_template` method and add the option `std` on top of average and median.

I wonder of the word 'template' would be good for std?
I was thinking template to be a representative waveform

2021-09-02 10:05 UTC, alejoe91 commented
Template stands for "average waveform". So in my opinion it also makes sense to also be able to return the template std. We could also have it as an optional return (e.g. with an extra arg `return_std=True/False`).

@samuelgarcia what do you think about it?

2021-09-02 12:40 UTC, samuelgarcia commented
No. I think I is really easy and intuitive to have
```python
template_mean = we.get_template('mean')
template_std = we.get_template('std')
```

2021-09-02 14:57 UTC, Saksham20 commented
> No. I think I is really easy and intuitive to have
> 
> ```python
> template_mean = we.get_template(unit_id, 'mean')
> template_std = we.get_template(unit_id, 'std')
> ```
> 
> We could also add some quartile stuff with the same method so.

okay, makes sense to put std also under templates. Will make those changes

2021-09-06 04:30 UTC, Saksham20 commented
@alejoe91 @samuelgarcia let me know what you think of the latest changes

2021-09-06 06:48 UTC, alejoe91 commented on spikeinterface/core/tests/test_waveform_extractor.py
> +    wf_qnt = we.get_all_templates(mode='std')
```suggestion
    wf_qnt = we.get_all_templates(mode='quantile')
```

??

2021-09-06 06:48 UTC, alejoe91 commented on spikeinterface/core/waveform_extractor.py
> +            'mean', 'median' (default), 'std'(standard deviation), 'quantile', quantile_value
`quantile_value` should be an extra argument with its own type and description

2021-09-06 06:49 UTC, alejoe91 requested changes
Thanks @Saksham20 

Just had a couple of small comments, the rest looks good :)

2021-09-07 07:34 UTC, alejoe91 approved these changes

2021-09-07 07:41 UTC, merged