Add more backwards compatibly for MockWaveformExtractor
SpikeInterface/spikeinterface pull request #2546
Opened 2024-03-06 12:50 UTC by chrishalcrow

Added several methods to MockWaveformExtractor and changed arguments in compute_blah_extensions function.

Will keep in draft until tests are added.

Added:
- format
- get_available_extension_names
- precompute_templates
- sample_spikes
- run_extract_waveforms
- select_units
- delete_extension
- get_random_spikes (new - without a way of computing some random spikes, you can't compute templates and other things)

to MockWaveformExtractor

I changed the FunctionFactory for the compute_blah_extensions (e.g. compute_principal_components, compute_templates) for backwards compatibility. Previously these took the form `compute_principal_components(waveform_extractor=we)` rather than `compute_principal_components(we)`.

Not added some methods. These involve: 
- Extension classes (extensions are now objects of a new extension class) so it's hard to see how these will not break (extensions, get_extension_class, is_extension, load_extension, register_extension)
- Loading stuff after loading your initial MockWaveformExtractor (load, load_from_folder, load_from zarr)
-Segments since SortingAnalyzer seems to deal with segments a bit differently (get_template_segment and get_waveform_segment).

2024-03-06 13:12 UTC, samuelgarcia commented
Hi Chris,
thanks for this. I will have a look soon.
As a general comments the goal of backward compatibility was more load/use old computation rather than load/use/recompute old computation.

2024-03-06 16:53 UTC, chrishalcrow commented
> Hi Chris, thanks for this. I will have a look soon. As a general comments the goal of backward compatibility was more load/use old computation rather than load/use/recompute old computation.

Sure. I was just aiming for as little broken as possible. With these changes, the pipelines in our lab work without any modification, and create lots of nice SortingAnalyzer folders as they go.

2024-03-12 14:18 UTC, alejoe91 requested changes
Added comments after discussion

2024-03-12 14:18 UTC, alejoe91 commented on src/spikeinterface/core/waveforms_extractor_backwards_compatibility.py
> +        sorting_analyzer.compute("random_spikes")
Remove this and add `sorting_analyzer.extensions["random_spikes"] = ext` after the `SelectRandomSpikes` is instantiated in `_read_old_waveforms_extractor_binary`

2024-03-12 14:18 UTC, alejoe91 commented on src/spikeinterface/core/waveforms_extractor_backwards_compatibility.py
> +        self.sorting_analyzer.compute("random_spikes")
Remove

2024-03-12 14:18 UTC, alejoe91 commented on src/spikeinterface/core/waveforms_extractor_backwards_compatibility.py
> +        self.sorting_analyzer.compute("waveforms")
Remove. The `MockWaveformExtractor` should not add new computations

2024-03-12 14:23 UTC, alejoe91 commented on src/spikeinterface/core/analyzer_extension_core.py
> +        ), "compute templates requires the random_spikes extension. You can run WaveformExtractor.get_random_spikes()"
```suggestion
        assert self.sorting_analyzer.has_extension(
            "random_spikes"
        ), "compute templates requires the random_spikes extension. You can run sorting_analyzer.get_random_spikes()"
```

2024-03-29 16:40 UTC, samuelgarcia approved these changes

2024-05-10 11:00 UTC, alejoe91 approved these changes

2024-05-10 13:32 UTC, merged