Add support for  for Intan "one-file-per-signal" and "one-file-per-channel" formats
SpikeInterface/spikeinterface pull request #2630
Opened 2024-03-26 20:05 UTC by h-mayorquin

As stated on the title. This is possible because we merged the following neo:

https://github.com/NeuralEnsemble/python-neo/pull/1402

As this translated cleanly the only thing that I am adding here are the tests.

2024-03-26 20:28 UTC, h-mayorquin commented
Interesting this fails here. It works locally for me but it is hard to know which of the tests is actually failing because of the structure of the tests with entities.

2024-03-26 22:34 UTC, h-mayorquin commented
Ok, the error was solved. The reason was that the tests were not using the latests versions of neo and probeinterface. That is, it seems that these lines are not working for the full tests:

https://github.com/SpikeInterface/spikeinterface/blob/2983463b655a6f10130b8017913f2ca90d4fd9fe/pyproject.toml#L153-L156

Probably something cache related. It is good for you to be aware of this @samuelgarcia @alejoe91

2024-03-27 06:06 UTC, alejoe91 commented on pyproject.toml
> +version = "0.101.0.dev0"
Can you revert this? See other PR 
```suggestion
version = "0.101.0"
```

2024-03-27 06:07 UTC, alejoe91 requested changes
Thanks @h-mayorquin 

Looks good, except for the change in version

2024-03-27 06:07 UTC, alejoe91 approved these changes

2024-03-27 06:07 UTC, alejoe91 commented
> Thanks @h-mayorquin
> 
> Looks good, except for the change in version

Changed

2024-03-27 11:48 UTC, merged