Move "return_scaled" options global to SortingAnalyzer.
SpikeInterface/spikeinterface pull request #2684
Opened 2024-04-09 13:58 UTC by samuelgarcia

Move "return_scaled" options global to SortingAnalyzer.

Having a unique and global option for this is less dangerous, for instance to compute snr which depends on 2 options.

2024-04-09 14:19 UTC, alejoe91 commented on src/spikeinterface/core/sortinganalyzer.py
> +    return_scaled: bool, default True
```suggestion
    return_scaled: bool, default: True
```

2024-04-09 14:19 UTC, alejoe91 commented on src/spikeinterface/core/sortinganalyzer.py
> +        print("create_sorting_analyzer: recording do not have scale to uV, force return_scaled=False")
```suggestion
        print("create_sorting_analyzer: recording does not have scaling to uV, forcing return_scaled=False")
```

2024-04-10 15:41 UTC, alejoe91 commented on src/spikeinterface/core/sparsity.py
> +            # ], "To compute sparsity from snr you need return_scaled=True for extensions"
```suggestion
```

2024-04-10 15:42 UTC, alejoe91 commented on src/spikeinterface/core/sparsity.py
> +            # ], "To compute sparsity from snr you need return_scaled=True for extensions"
```suggestion
```

2024-04-10 15:42 UTC, alejoe91 commented on src/spikeinterface/core/sparsity.py
> +        # assert ext.params["return_scaled"], "To compute sparsity from snr you need return_scaled=True for extensions"
```suggestion
```

2024-04-10 15:43 UTC, alejoe91 commented on src/spikeinterface/core/waveforms_extractor_backwards_compatibility.py
> +    return_scaled = (params["return_scaled"],)
Why not just 
```suggestion
    return_scaled = params["return_scaled"]
```
???

2024-04-10 15:44 UTC, alejoe91 requested changes
@samuelgarcia see comments

2024-04-10 15:47 UTC, samuelgarcia commented on src/spikeinterface/postprocessing/tests/test_spike_amplitudes.py
>      ]
No because we want at least one test.

2024-04-10 15:57 UTC, alejoe91 commented on src/spikeinterface/postprocessing/tests/test_spike_amplitudes.py
>      ]
I thought this was default behavior

2024-04-10 15:58 UTC, alejoe91 approved these changes

2024-04-11 08:02 UTC, merged