Standardize colon spacing in docstrings
SpikeInterface/spikeinterface pull request #2950
Opened 2024-05-31 13:27 UTC by chrishalcrow

Standardize colon spacings in docstrings.

All public functions now use the numpydoc colon spacing (https://numpydoc.readthedocs.io/en/latest/format.html#parameters). Meaning that they look like
```
recording : RecordingExtractor
    The recording extractor object to be saved in .dat format
```
rather than
```
recording: RecordingExtractor
    The recording extractor object to be saved in .dat format
```

This means we can use the `numpydoc_validation_checks = {"PR01"}` sphinx parameter to easily check for conflicts between function/class arguments and their documented names.

The format is also consistent with the standard numpydoc autodoc generator (https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring).

2024-05-31 13:44 UTC, zm711 reviewed
Fix the default `:`

2024-06-01 11:23 UTC, alejoe91 requested changes
Thanks @chrishalcrow 

Just a little comment!

2024-06-01 11:23 UTC, alejoe91 commented on src/spikeinterface/comparison/paircomparisons.py
> +num_bad : {num_bad}
@chrishalcrow these are for printing the performance, so I think we can revert

2024-06-03 13:42 UTC, zm711 commented on src/spikeinterface/core/sparsity.py
> +    method : str
Since this is an injected docstring does the numpydoc validation still work the same?

2024-06-03 14:34 UTC, alejoe91 approved these changes

2024-06-03 20:53 UTC, zm711 approved these changes
This looks great to me. Chris could you remember to also change our docstring contributing guide to account for this?

2024-06-04 08:42 UTC, alejoe91 commented
Thanks @chrishalcrow ! Let's merge :)

2024-06-04 09:42 UTC, merged

2024-06-04 09:53 UTC, samuelgarcia commented
Thanks a lot Chris for this super tedious but usefull fight.