extractor_dict_iterator for solving path detection in object `kwargs`
SpikeInterface/spikeinterface pull request #3089
Opened 2024-06-26 23:03 UTC by h-mayorquin

2024-06-27 07:02 UTC, alejoe91 requested changes
@h-mayorquin I love this! just some renaming suggestions

2024-06-27 07:02 UTC, alejoe91 commented on src/spikeinterface/core/core_tools.py
> +# This is the current definition that an element in a recording_dict is a path
```suggestion
# This is the current definition that an element in an extractor_dict is a path
```

2024-06-27 07:03 UTC, alejoe91 commented
@h-mayorquin this should cloe #3014 right?

2024-06-27 13:52 UTC, h-mayorquin commented on src/spikeinterface/core/core_tools.py
> +recording_dict_element = namedtuple(typename="recording_dict_element", field_names=["value", "name", "access_path"])
Yes, I made that mistake at the beginning and this renaming escape me. Will change!

2024-06-27 14:41 UTC, h-mayorquin commented
@alejoe91 did the correction and yes, this should close #3041

2024-06-27 14:47 UTC, alejoe91 commented
@h-mayorquin can you make the previous test function in `test_core_tools` (`test_path_utils_functions`) also to use `pytest.skip`?

2024-06-27 15:01 UTC, h-mayorquin commented
Yes, done.

2024-06-27 15:07 UTC, alejoe91 commented
This looks good to me. Much much cleaner than the old presentation!

@samuelgarcia what do you think?

2024-06-27 15:07 UTC, alejoe91 approved these changes

2024-06-28 10:17 UTC, samuelgarcia commented
> I guess at the beginning the purpose of the function was both iterating overt the dict and also modifying the values. But then, some other functions appeared like `get_path_list` that use `recursive_path_modifier` to iterate over the extractor and accumulate path-like values.

Excellent guess and analysis of the histical reason!
I wanted to do something similar to this PR this when impleneted _get_paths_list but was to lazy to refacor with the yield like you did.

Thanks a lot for this effort.

2024-06-28 10:19 UTC, samuelgarcia commented on src/spikeinterface/core/core_tools.py
> +                    v, access_path + (i,), name=name
This is really smart to have the path both with key and index for list!!

2024-06-28 10:23 UTC, samuelgarcia commented on src/spikeinterface/core/core_tools.py
> +extractor_dict_element = namedtuple(typename="extractor_dict_element", field_names=["value", "name", "access_path"])
very good idea!

2024-06-28 10:23 UTC, merged