Add PreprocessingPipeline
SpikeInterface/spikeinterface pull request #3438
Opened 2024-09-25 10:13 UTC by chrishalcrow

A proposal to add a `PreprocessingPipeline` class, which contains ordered preprocessing steps and their kwargs in a dictionary. 

You can apply the class to a `recording`, or use the helper function `create_preprocessed` to make a preprocessed recording:

``` python
preprocessor_dict = {'bandpass_filter': {'freq_max': 3000}, 'common_reference': {}}

# apply using
from spikeinterface.preprocessing import PreprocessingPipeline
pipeline = PreprocessingPipeline(preprocessor_dict)
preprocessed_recording = pipeline.apply_to(recording)

# or
from spikeinterface.preprocessing import create_preprocessed
preprocessed_recording = create_preprocessed(recording, preprocessor_dict)
```

Also adds a function which takes in a `recording.json` provenance file and make a `preprocessor_dict`:

``` python
from spikeinterface.preprocessing import get_preprocessing_dict_from_json
my_dict = get_preprocessing_dict_from_json('/path/to/recording.json')
```

This allow for some cool things:
1. Users can pass a single dictionary to construct a preprocessed recording (as above). Hence it completes the “dictionary workflow”; since you can use dicts in sorting, `run_sorter_jobs`,  and postprocessing in `compute`.
2. Users can easily visualise their preprocessing pipeline using the repr, including an HTML repr in Jupyter notebook (I made a _hideous_ one, but we can aim for something like the sklearn pipeline repr see https://scikit-learn.org/stable/auto_examples/miscellaneous/plot_pipeline_display.html)
3. Increases portability between labs, since you can reconstruct the preprocessing steps from the `recording.json` file without the original recording (and worrying about paths).

Note that 3. only works for preprocessing steps that are in some sense “global” i.e. can be applied to _any_ recording. This doesn’t apply for all preprocessing steps e.g. `interpolate_bad_channels` needs the `bad_unit_ids` which are recording dependent. However, many of these functions can be modified to be applied more globally e.g. if `bad_unit_ids` is `None`, `interpolate_bad_channels` could detect bad channels, then interpolate these. This would be apply-able to any recording, so is “global”.

No rush on this and I’m not 100% set on it being implemented. Important to get the names right. I read this: https://melevir.medium.com/python-functions-naming-tips-376f12549f9. I think it’s important that `create_preprocessed` doesn’t sound in-place, after the number of problems with `set_probe`. Hence I’m against something like `apply_preprocessing(recording)`, and would rather have `make`, `create`, `construct`, `produce` or something in the function name. I also like the idea (from the article) that you don’t need to include e.g. `recording` in the name if `recording` is a required argument. Hence I like something like `my_pipeline.apply_to(recording)` rather than something like `my_pipeline.apply_pipeline_to_recording(recording)`.

To do:
- Tests
- Add "allowed preprocessing steps" for `get_preprocessing_dict_from_json`

2025-06-13 15:10 UTC, zm711 reviewed
I guess I'm out of the loop on this. So I'm not sure how helpful my review of code would be. I would prefer to hear what Alessio and Sam think to feel safe. I think my only concern is that dictionaries since 3.7 maintain order of insertion, but since preprocessing steps are ordered (doing filtering then whitening is not the same as whitening then filtering) I would feel more comfortable if we had some way to guarantee the order rather than relying on dictionary implementation details since they've changed once before. Right?

2025-06-13 15:10 UTC, zm711 commented on src/spikeinterface/preprocessing/pipeline.py
> +                )
Wouldn't it make sense to check all preprocessors add them to a list if not possible and raise a type error with all problematic preprocessors at once rather than make the person run it and then try again only to realize they made a typo in their third key?

2025-06-13 15:10 UTC, zm711 commented on src/spikeinterface/preprocessing/pipeline.py
> +    recording: BaseRecording, pipeline_or_dict: dict | PreprocessingPipeline = {}, apply_precomputed_kwargs=True
Isn't an empty dict as the default dangerous for inplace modification? Would it make more sense to be required and not add the default?

2025-06-13 15:10 UTC, zm711 commented on src/spikeinterface/preprocessing/pipeline.py
> +    _load_pp_from_dict(provenance_dict, pipeline_dict_from_provenance)
shouldn't this return something?

2025-06-16 07:05 UTC, chrishalcrow commented on src/spikeinterface/preprocessing/pipeline.py
> +                )
oooh, nice idea. Done!

2025-06-16 07:06 UTC, chrishalcrow commented on src/spikeinterface/preprocessing/pipeline.py
> +    recording: BaseRecording, pipeline_or_dict: dict | PreprocessingPipeline = {}, apply_precomputed_kwargs=True
yes yes yes, 100 times yes. Thanks!

2025-06-16 07:08 UTC, chrishalcrow commented on src/spikeinterface/preprocessing/pipeline.py
> +    _load_pp_from_dict(provenance_dict, pipeline_dict_from_provenance)
This `_load_pp_from_dict` is a gross recursive function since our provenance json/pkl are gross recursive dicts. Due to this structure, it returns the kwargs of the recursive step it's at. So it does return something, but the important bit of the function is that it modifies `pipeline_dict_from_provenance`. It does return something, so maybe it's best practice to put that returned value somewhere (which I've done). I've also significantly updated the `_load_pp_from_dict` docstring and variable names, which should hopefully make the purpose of the function clearer.

2025-06-16 07:15 UTC, chrishalcrow commented
> I guess I'm out of the loop on this. So I'm not sure how helpful my review of code would be. I would prefer to hear what Alessio and Sam think to feel safe. I think my only concern is that dictionaries since 3.7 maintain order of insertion, but since preprocessing steps are ordered (doing filtering then whitening is not the same as whitening then filtering) I would feel more comfortable if we had some way to guarantee the order rather than relying on dictionary implementation details since they've changed once before. Right?

It was incredibly helpful - thanks!!

They made the change in 3.6, and from 3.7 it was added to the language spec ("Changed in version 3.7: Dictionary order is guaranteed to be insertion order." from the bottom of https://docs.python.org/3/library/stdtypes.html#dict), as ruled by Guido (https://mail.python.org/pipermail/python-dev/2017-December/151283.html). So I think it's pretty safe.

Not against implementing `OrderedDict`s under the hood, but I'd prefer to allow the user to pass a plain dict, to avoid them having to `from collections import OrderedDict`. If we used `OrderdDict`s in the codebase, it would be pretty easy to update if python broke dictionary ordering. But I'm personally in favour of keeping it the way it is. The tests will (sometimes) fail if ordered is removed.

2025-06-16 15:58 UTC, alejoe91 requested changes
Thanks for this amazing work Chris! My main point is to make the functions more generally available to recordings, not just provenance files.

2025-06-16 15:58 UTC, alejoe91 commented on doc/modules/preprocessing.rst
> +with a minimum frequency of 250 Hz followed by whitening with default parameters, we first make the appropriate dictionary
missing detect and remove step

2025-06-16 15:58 UTC, alejoe91 commented on doc/modules/preprocessing.rst
> +
You could paste html here, right?

2025-06-16 15:58 UTC, alejoe91 commented on src/spikeinterface/preprocessing/pipeline.py
> +def get_preprocessing_dict_from_provenance(recording_provenance_path):
I don't think this needs to be `provenance`, since you could pass it any json/pkl recording file. What about `get_preprocessing_pipeline_from_file`?

2025-06-16 15:58 UTC, alejoe91 commented on src/spikeinterface/preprocessing/pipeline.py
> +    Recursive function used to iterate through a recording provenance dictionary,
```suggestion
    Recursive function used to iterate through a recording dictionary,
```
ditto

2025-06-16 15:58 UTC, alejoe91 commented on src/spikeinterface/preprocessing/pipeline.py
> +def _load_pp_from_dict(prov_dict, kwargs_dict):
I would make this public. It could be helpful

2025-06-16 15:58 UTC, alejoe91 commented on src/spikeinterface/preprocessing/pipeline.py
> +        apply_precomputed_kwargs : Bool, default: False
```suggestion
        apply_precomputed_kwargs : bool, default: False
```

2025-06-16 15:58 UTC, alejoe91 commented on src/spikeinterface/preprocessing/pipeline.py
> +        recording : RecordingExtractor
```suggestion
        recording : BaseRecording
```

2025-06-16 15:58 UTC, alejoe91 commented on src/spikeinterface/preprocessing/pipeline.py
> +def _load_pp_from_dict(prov_dict, kwargs_dict):
@chrishalcrow could you add a `load_preprocessing_pipeline_from_analyzer`? It could be very helpful (both from binary_folder and zarr)

2025-06-17 12:39 UTC, chrishalcrow commented on src/spikeinterface/preprocessing/pipeline.py
> +def get_preprocessing_dict_from_provenance(recording_provenance_path):
Yup, sounds good. 

Note: I prefer to return the `dict` than a `PreprocessingPipeline` itself since this allows the user to then use `apply_pipeline(recording, pipeline_dict)` and to share it easily. But I could be convinced otherwise!

2025-06-17 12:41 UTC, chrishalcrow commented on src/spikeinterface/preprocessing/pipeline.py
> +def _load_pp_from_dict(prov_dict, kwargs_dict):
I've added a `get_preprocessing_dict_from_analyzer` function plus tests.

2025-06-17 12:42 UTC, chrishalcrow commented on src/spikeinterface/preprocessing/pipeline.py
> +def _load_pp_from_dict(prov_dict, kwargs_dict):
I'm against this. Mostly because this funcitons main purpose is to modify `kwargs_dict`. So it doesn't return what you would naively expect. It's like this to make the recursive loading work. In this last round of refactoring, I've added a `_make_pipeline_dict_from_recording_dict` - maybe that could be made public?? Do you really think it's helpful?

2025-06-17 12:42 UTC, chrishalcrow commented on src/spikeinterface/preprocessing/pipeline.py
> +def _load_pp_from_dict(prov_dict, kwargs_dict):
And yes - a great idea!!

2025-06-17 13:12 UTC, chrishalcrow commented
Tests failing due to #3990

2025-06-17 17:24 UTC, alejoe91 commented
LGTM! Thanks Chris this is going to be supeeeer helpful!

2025-06-17 17:26 UTC, zm711 commented on examples/how_to/build_pipeline_with_dicts.py
> +# data. Once your happy, you then need to build a sturdy, consistent pipeline to process all
```suggestion
# data. Once you're happy, you then need to build a sturdy, consistent pipeline to process all
```
:P

2025-06-17 17:27 UTC, zm711 commented on doc/how_to/build_pipeline_with_dicts.rst
> +with to get everything working with your data. Once your happy, you then
```suggestion
with to get everything working with your data. Once you're happy, you then
```
```suggestion
with to get everything working with your data. Once your happy, you then
```

2025-06-17 17:28 UTC, zm711 commented
Not required I guess, but we could fix both of them once tests pass so that we don't forget to fix in the future.

2025-06-18 08:38 UTC, chrishalcrow commented
Just fixed a couple of lil doc things - happy once tests pass :)

2025-06-18 13:48 UTC, zm711 approved these changes
I didn't reread the code, but at least from the documentation side this looks good to me too

2025-06-18 13:48 UTC, zm711 commented on src/spikeinterface/preprocessing/pipeline.py
> +pp_names_to_classes = {pp_function.__name__: pp_class for pp_class, pp_function in _all_preprocesser_dict.items()}
As an aside if we are actually going to use this private dict then I probably shouldn't have left the typo as an homage to history :). We should consider fixing that in another PR....

2025-06-18 15:20 UTC, alejoe91 commented
Ok to merge for me. @samuelgarcia ok?

2025-06-19 10:22 UTC, merged