use context manager ot open and close nwb files
SpikeInterface/spikeinterface pull request #378
Opened 2021-11-21 12:44 UTC by Saksham20

currently the nwbextractors keep the nwbfile open.  THis PR uses context manager `NWBHDF5IO` to take care of this

2021-11-22 07:51 UTC, samuelgarcia commented
Hi @Saksham20.
After discussion, @alejoe91 did the very oposite refactoring very recently. See #352

The context manager do not work for extractor because the file need to stay open to retrieve chunks and time vector.
The cost of open/close is high, we cannot afford this at every chunk reading.
So the classic approach of open once and close at the end is more efficient in readers.

2021-11-22 08:58 UTC, alejoe91 commented
Maybe adding a `__del__` to close the io should do it

2021-11-22 11:47 UTC, samuelgarcia commented
I don't think we should play with the `__del__` since it is already implemented at nwb/hdf5 level.
It is beter to leave the low level liobs handle low level close at good timing.

2021-11-22 12:27 UTC, alejoe91 commented
No, because they makes it fail on windows when we try to delete the file

2021-11-22 12:55 UTC, samuelgarcia commented
Lets do a `del  rec` before playing with the `__del__`

2021-11-22 12:59 UTC, alejoe91 commented
> Lets do a `del rec` before playing with the `__del__`

where? I think that everytime the object is deleted the io should be closed

2021-11-23 11:45 UTC, alejoe91 commented on spikeinterface/extractors/nwbextractors.py
> -        timestamps = None
@Saksham20 this needs to stay here

2021-11-23 11:45 UTC, alejoe91 commented on spikeinterface/extractors/nwbextractors.py
> +            timestamps = None
remove

2021-11-23 11:46 UTC, alejoe91 requested changes
@Saksham20 same mechanism should be implemented to the SortingExtractor too

2021-11-23 13:05 UTC, alejoe91 approved these changes

2021-11-23 13:05 UTC, merged